openapi: 3.0.3

paths:
  /api/example:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          $ref: "#/components/responses/ErrorResponse"
        401:
          $ref: "#/components/responses/ErrorResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
  /api/more:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          $ref: "#/components/responses/ErrorResponse"
        401:
          $ref: "#/components/responses/ErrorResponse"
        404:
          $ref: "#/components/responses/ErrorResponse"
          
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        extra:
          type: string
  responses:
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
